package entities;
// Generated Dec 15, 2018 6:18:31 PM by Hibernate Tools 4.3.1



/**
 * Card generated by hbm2java
 */
public class Card  implements java.io.Serializable {


     private Integer cardId;
     private User user;
     private String seri;

    public Card() {
    }

	
    public Card(User user) {
        this.user = user;
    }
    public Card(User user, String seri) {
       this.user = user;
       this.seri = seri;
    }
   
    public Integer getCardId() {
        return this.cardId;
    }
    
    public void setCardId(Integer cardId) {
        this.cardId = cardId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getSeri() {
        return this.seri;
    }
    
    public void setSeri(String seri) {
        this.seri = seri;
    }




}


