package entities;
// Generated Nov 24, 2018 11:18:59 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Card generated by hbm2java
 */
@Entity
@Table(name="card"
    ,catalog="btl_schedule"
)
public class Card  implements java.io.Serializable {


     private Integer cardId;
     private User user;
     private String seri;

    public Card() {
    }

	
    public Card(User user) {
        this.user = user;
    }
    public Card(User user, String seri) {
       this.user = user;
       this.seri = seri;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="card_id", unique=true, nullable=false)
    public Integer getCardId() {
        return this.cardId;
    }
    
    public void setCardId(Integer cardId) {
        this.cardId = cardId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="seri", length=45)
    public String getSeri() {
        return this.seri;
    }
    
    public void setSeri(String seri) {
        this.seri = seri;
    }




}


