package entities;
// Generated Nov 24, 2018 11:18:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Registration generated by hbm2java
 */
@Entity
@Table(name="registration"
    ,catalog="btl_schedule"
)
public class Registration  implements java.io.Serializable {


     private int registerId;
     private Shift shift;
     private User user;
     private Date day;
     private Boolean active;
     private Date checkIn;
     private Date checkOut;

    public Registration() {
    }

	
    public Registration(int registerId, Shift shift, User user) {
        this.registerId = registerId;
        this.shift = shift;
        this.user = user;
    }
    public Registration(int registerId, Shift shift, User user, Date day, Boolean active, Date checkIn, Date checkOut) {
       this.registerId = registerId;
       this.shift = shift;
       this.user = user;
       this.day = day;
       this.active = active;
       this.checkIn = checkIn;
       this.checkOut = checkOut;
    }
   
     @Id 

    
    @Column(name="register_id", unique=true, nullable=false)
    public int getRegisterId() {
        return this.registerId;
    }
    
    public void setRegisterId(int registerId) {
        this.registerId = registerId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="shift_id", nullable=false)
    public Shift getShift() {
        return this.shift;
    }
    
    public void setShift(Shift shift) {
        this.shift = shift;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="day", length=10)
    public Date getDay() {
        return this.day;
    }
    
    public void setDay(Date day) {
        this.day = day;
    }

    
    @Column(name="active")
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="check_in", length=10)
    public Date getCheckIn() {
        return this.checkIn;
    }
    
    public void setCheckIn(Date checkIn) {
        this.checkIn = checkIn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="check_out", length=10)
    public Date getCheckOut() {
        return this.checkOut;
    }
    
    public void setCheckOut(Date checkOut) {
        this.checkOut = checkOut;
    }




}


