package entities;
// Generated Dec 15, 2018 6:18:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Restaurent generated by hbm2java
 */
public class Restaurent  implements java.io.Serializable {


     private Integer restaurentId;
     private RestaurentMaster restaurentMaster;
     private String restaurentName;
     private String address;
     private Set users = new HashSet(0);

    public Restaurent() {
    }

	
    public Restaurent(RestaurentMaster restaurentMaster) {
        this.restaurentMaster = restaurentMaster;
    }
    public Restaurent(RestaurentMaster restaurentMaster, String restaurentName, String address, Set users) {
       this.restaurentMaster = restaurentMaster;
       this.restaurentName = restaurentName;
       this.address = address;
       this.users = users;
    }
   
    public Integer getRestaurentId() {
        return this.restaurentId;
    }
    
    public void setRestaurentId(Integer restaurentId) {
        this.restaurentId = restaurentId;
    }
    public RestaurentMaster getRestaurentMaster() {
        return this.restaurentMaster;
    }
    
    public void setRestaurentMaster(RestaurentMaster restaurentMaster) {
        this.restaurentMaster = restaurentMaster;
    }
    public String getRestaurentName() {
        return this.restaurentName;
    }
    
    public void setRestaurentName(String restaurentName) {
        this.restaurentName = restaurentName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


