package entities;
// Generated Nov 24, 2018 11:18:59 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RestaurentMaster generated by hbm2java
 */
@Entity
@Table(name="restaurent_master"
    ,catalog="btl_schedule"
)
public class RestaurentMaster  implements java.io.Serializable {


     private Integer masterId;
     private String masterName;
     private Set<Restaurent> restaurents = new HashSet<Restaurent>(0);

    public RestaurentMaster() {
    }

    public RestaurentMaster(String masterName, Set<Restaurent> restaurents) {
       this.masterName = masterName;
       this.restaurents = restaurents;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="master_id", unique=true, nullable=false)
    public Integer getMasterId() {
        return this.masterId;
    }
    
    public void setMasterId(Integer masterId) {
        this.masterId = masterId;
    }

    
    @Column(name="master_name", length=245)
    public String getMasterName() {
        return this.masterName;
    }
    
    public void setMasterName(String masterName) {
        this.masterName = masterName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="restaurentMaster")
    public Set<Restaurent> getRestaurents() {
        return this.restaurents;
    }
    
    public void setRestaurents(Set<Restaurent> restaurents) {
        this.restaurents = restaurents;
    }




}


