package entities;
// Generated Dec 15, 2018 6:18:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Shift generated by hbm2java
 */
public class Shift  implements java.io.Serializable {


     private Integer shiftId;
     private Integer shiftType;
     private Set registrations = new HashSet(0);

    public Shift() {
    }

    public Shift(Integer shiftType, Set registrations) {
       this.shiftType = shiftType;
       this.registrations = registrations;
    }
   
    public Integer getShiftId() {
        return this.shiftId;
    }
    
    public void setShiftId(Integer shiftId) {
        this.shiftId = shiftId;
    }
    public Integer getShiftType() {
        return this.shiftType;
    }
    
    public void setShiftType(Integer shiftType) {
        this.shiftType = shiftType;
    }
    public Set getRegistrations() {
        return this.registrations;
    }
    
    public void setRegistrations(Set registrations) {
        this.registrations = registrations;
    }




}


