package entities;
// Generated Nov 24, 2018 11:18:59 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Shift generated by hbm2java
 */
@Entity
@Table(name="shift"
    ,catalog="btl_schedule"
)
public class Shift  implements java.io.Serializable {


     private Integer shiftId;
     private Integer shiftType;
     private Set<Registration> registrations = new HashSet<Registration>(0);

    public Shift() {
    }

    public Shift(Integer shiftType, Set<Registration> registrations) {
       this.shiftType = shiftType;
       this.registrations = registrations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="shift_id", unique=true, nullable=false)
    public Integer getShiftId() {
        return this.shiftId;
    }
    
    public void setShiftId(Integer shiftId) {
        this.shiftId = shiftId;
    }

    
    @Column(name="shift_type")
    public Integer getShiftType() {
        return this.shiftType;
    }
    
    public void setShiftType(Integer shiftType) {
        this.shiftType = shiftType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="shift")
    public Set<Registration> getRegistrations() {
        return this.registrations;
    }
    
    public void setRegistrations(Set<Registration> registrations) {
        this.registrations = registrations;
    }




}


