package entities;
// Generated Nov 24, 2018 11:18:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="btl_schedule"
)
public class User  implements java.io.Serializable {


     private Integer userId;
     private Restaurent restaurent;
     private String userName;
     private String password;
     private String numberPhone;
     private String email;
     private String address;
     private String fullName;
     private Float coefficient;
     private Date createAt;
     private Date updateAt;
     private Set<Registration> registrations = new HashSet<Registration>(0);
     private Set<Card> cards = new HashSet<Card>(0);

    public User() {
    }

	
    public User(Restaurent restaurent) {
        this.restaurent = restaurent;
    }
    public User(Restaurent restaurent, String userName, String password, String numberPhone, String email, String address, String fullName, Float coefficient, Date createAt, Date updateAt, Set<Registration> registrations, Set<Card> cards) {
       this.restaurent = restaurent;
       this.userName = userName;
       this.password = password;
       this.numberPhone = numberPhone;
       this.email = email;
       this.address = address;
       this.fullName = fullName;
       this.coefficient = coefficient;
       this.createAt = createAt;
       this.updateAt = updateAt;
       this.registrations = registrations;
       this.cards = cards;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="user_id", unique=true, nullable=false)
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="restaurent_id", nullable=false)
    public Restaurent getRestaurent() {
        return this.restaurent;
    }
    
    public void setRestaurent(Restaurent restaurent) {
        this.restaurent = restaurent;
    }

    
    @Column(name="user_name", length=45)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="password", length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="number_phone", length=45)
    public String getNumberPhone() {
        return this.numberPhone;
    }
    
    public void setNumberPhone(String numberPhone) {
        this.numberPhone = numberPhone;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="address", length=245)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="full_name", length=45)
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    
    @Column(name="coefficient", precision=12, scale=0)
    public Float getCoefficient() {
        return this.coefficient;
    }
    
    public void setCoefficient(Float coefficient) {
        this.coefficient = coefficient;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="create_at", length=10)
    public Date getCreateAt() {
        return this.createAt;
    }
    
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="update_at", length=10)
    public Date getUpdateAt() {
        return this.updateAt;
    }
    
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Registration> getRegistrations() {
        return this.registrations;
    }
    
    public void setRegistrations(Set<Registration> registrations) {
        this.registrations = registrations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Card> getCards() {
        return this.cards;
    }
    
    public void setCards(Set<Card> cards) {
        this.cards = cards;
    }




}


