package entities;
// Generated Dec 15, 2018 6:18:31 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private Restaurent restaurent;
     private String numberPhone;
     private String email;
     private String address;
     private String fullName;
     private Float coefficient;
     private Date createAt;
     private Date updateAt;
     private Set registrations = new HashSet(0);
     private Set cards = new HashSet(0);

    public User() {
    }

	
    public User(Restaurent restaurent) {
        this.restaurent = restaurent;
    }
    public User(Restaurent restaurent, String numberPhone, String email, String address, String fullName, Float coefficient, Date createAt, Date updateAt, Set registrations, Set cards) {
       this.restaurent = restaurent;
       this.numberPhone = numberPhone;
       this.email = email;
       this.address = address;
       this.fullName = fullName;
       this.coefficient = coefficient;
       this.createAt = createAt;
       this.updateAt = updateAt;
       this.registrations = registrations;
       this.cards = cards;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Restaurent getRestaurent() {
        return this.restaurent;
    }
    
    public void setRestaurent(Restaurent restaurent) {
        this.restaurent = restaurent;
    }
    public String getNumberPhone() {
        return this.numberPhone;
    }
    
    public void setNumberPhone(String numberPhone) {
        this.numberPhone = numberPhone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public Float getCoefficient() {
        return this.coefficient;
    }
    
    public void setCoefficient(Float coefficient) {
        this.coefficient = coefficient;
    }
    public Date getCreateAt() {
        return this.createAt;
    }
    
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }
    public Date getUpdateAt() {
        return this.updateAt;
    }
    
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }
    public Set getRegistrations() {
        return this.registrations;
    }
    
    public void setRegistrations(Set registrations) {
        this.registrations = registrations;
    }
    public Set getCards() {
        return this.cards;
    }
    
    public void setCards(Set cards) {
        this.cards = cards;
    }




}


